### ISSUE TITLE
Pet's image is aligned to the left in the give in adoption view

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#409]
**Preconditions**
- User has a valid username and password in the platform
- User has at least one pet registered
- User is logged in

**Steps to reproduce**
- Click in the adoption main menu
- Click in the button with label "Give in Adoption"

**Expectation**
- Pet's image is center aligned as the rest of the fields

**Actual result**
- Pet's image is aligned to the left

**Screenshot**
![give_in_adoption](https://github.com/user-attachments/assets/8510918b-51e2-4973-baea-5cd0970dd329)

**Comment by tkim602** [comment]
if it is not fixed yet, can I give it a try?

**Comment by josdem** [comment]
> if it is not fixed yet, can I give it a try?

Absolutely, thank you! let me know if any questions.

**Comment by tkim602** [comment]
@josdem 
Hi, I’m trying to run the project, but I keep encountering a database connection error: 

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured. Failed to determine a suitable driver class

I’ve verified that my application-development.yml has the correct database configuration, and I’ve set -Dspring.config.location=$HOME/.vetlog/application-development.yml as the config path. 

Could you advise on what I might be missing to resolve this?

**Comment by josdem** [comment]
Hi @tkim602 according to the wiki page the command you should use to run the app is:
```bash
./gradlew -Dspring.config.location=$HOME/.vetlog/application-development.yml -Dflyway.user=${username} -Dflyway.password=${password} bootRun
```
Please find here a copy from my local computer `application-development.yml` file:
```yaml
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/vetlog
    username:  username
    password:  password
    driverClassName: com.mysql.jdbc.Driver
    maxActive:  50
    maxIdle: 5
    minIdle: 25
    initialSize: 10
    validationQuery: SELECT 1
    testOnBorrow: true
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    maxWait: 10000
    template:
    cache: false
  jpa:
    hibernate:
      DdlAuto: validate
  profiles:
    include: development
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  cloud:
    gcp:
      projectId: vetlog-357216
      core:
        enabled: true
      credentials:
        location: classpath:vetlog.json
message: Hello Vetlog!
jmailer:
  url: https://jmailer.josdem.io/emailer/
  path: message
baseUrl: https://vetlog.org/
template:
  register:
    name: register.ftl
    path: recovery/activate/
  forgot:
    name: forgotPassword.ftl
    path: recovery/forgot/
  adoption:
    name: adoption.ftl
breedsByTypeUrl: https://vetlog.org/breed/list
imageBucket: vetlog-bucket
prescriptionBucket: prescription-bucket
gcpUrl: https://storage.googleapis.com/
defaultImage: default-image.png
token: jmailer-user-token
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
```

Also make sure you are able to connect to your local database computer using any client such as command line or [MySQL Workbench][https://www.mysql.com/products/workbench/]. I hope this helps, let me know if you still are facing issues.
